// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import Snackbar from 'react-native-snackbar';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} message
 * @param {Nanoflow} action_callback
 * @param {string} action_text
 * @param {string} action_color
 * @returns {Promise.<void>}
 */
export async function JSA_ShowSnackBarWithAction(message, action_callback, action_text, action_color) {
	// BEGIN USER CODE
	Snackbar.show({
		text: message,
		duration: Snackbar.LENGTH_INDEFINITE,
		action: {
			text: action_text,
			textColor: action_color,
			onPress: async () => {
				await action_callback();
			},
		},
	});
	// END USER CODE
}
